### ISSUE TITLE
When Running Commands in console they throw an error

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/SmUtility#2]
When running commands like `/alert` or `/send` in console it throws this error

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command alert e for com.velocitypowered.proxy.console.VelocityConsole@57d6c5e1
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command alert e for com.velocitypowered.proxy.console.VelocityConsole@57d6c5e1
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.Player.getGameProfile()" because "player" is null
        at me.smudge.smutility.UtilityPlayer.<init>(UtilityPlayer.java:40) ~[?:?]
        at me.smudge.smutility.commands.Command.execute(Command.java:58) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```

**Velocity Version**
```
[11:22:53 INFO]: Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)
[11:22:53 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[11:22:53 INFO]: velocitypowered.com - GitHub
```

**Comment by Smudgge** [comment]
Ive put in a fix for this bug in the next update, let me know if this still occurs
